version: 2.1

orbs:
  codacy: codacy/base@1.0.0

jobs:
  build_image:
    executor: codacy/machine
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build base docker image
          command: make -C base-image
      - run:
          name: Build docker image
          command: make -C config-reloader build-image VERSION=$(cat .version) TAG=$(cat .version) IMAGE="codacy/$CIRCLE_PROJECT_REPONAME"
      - run:
          name: Save docker image
          command: mkdir target && docker save --output target/docker-image.tar codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
      - persist_to_workspace:
          paths:
            - workdir/target
          root: ~/

  docker_push:
    executor: codacy/machine
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker image
          command: docker load --input target/docker-image.tar
      - deploy:
          name: Publish docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)

workflows:
  lint_and_publish:
    jobs:
      - codacy/checkout_and_version
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint log-router
          requires:
            - codacy/checkout_and_version
      - build_image:
          requires:
            - codacy/checkout_and_version

      # Only in master
      - docker_push:
          context: CodacyDocker
          requires:
            - helm_lint
            - build_image
          filters:
            branches:
              only:
                - master
                - feature/custom-stdout
      - codacy/helm_push:
          name: helm_push_external
          context: CodacyHelm
          chart_name: log-router
          helm_dir: ./
          charts_repo_url: "https://charts.codacy.com/external"
          requires:
            - docker_push
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          requires:
            - helm_push_external
